# Vote Escrow
INVALID_TIME = "INVALID_TIME"
LOCK_IS_ATTACHED = "LOCK_IS_ATTACHED"
LOCK_HAS_EXPIRED = "LOCK_HAS_EXPIRED"
INVALID_LOCK_TIME = "INVALID_LOCK_TIME"
LOCK_YET_TO_EXPIRE = "LOCK_YET_TO_EXPIRE"
INFLATION_NOT_ADDED = "INFLATION_NOT_ADDED"
TOO_EARLY_TIMESTAMP = "TOO_EARLY_TIMESTAMP"
LOCK_DOES_NOT_EXIST = "LOCK_DOES_NOT_EXIST"
INVALID_INCREASE_VALUE = "INVALID_INCREASE_VALUE"
ALREADY_CLAIMED_INFLATION = "ALREADY_CLAIMED_INFLATION"
INVALID_INCREASE_END_TIMESTAMP = "INVALID_INCREASE_END_TIMESTAMP"

# Voter
EPOCH_ENDED = "EPOCH_ENDED"
INVALID_EPOCH = "INVALID_EPOCH"
ZERO_VOTE_NOT_ALLOWED = "ZERO_VOTE_NOT_ALLOWED"
SENDER_DOES_NOT_OWN_LOCK = "SENDER_DOES_NOT_OWN_LOCK"
PREVIOUS_EPOCH_YET_TO_END = "PREVIOUS_EPOCH_YET_TO_END"
NOT_ENOUGH_VOTING_POWER_AVAILABLE = "NOT_ENOUGH_VOTING_POWER_AVAILABLE"

# Bribe
EPOCH_IN_THE_PAST = "EPOCH_IN_THE_PAST"
EPOCH_NOT_YET_OVER = "EPOCH_NOT_YET_OVER"
INCORRECT_TEZ_VALUE_SENT = "INCORRECT_TEZ_VALUE_SENT"
INVALID_BRIBE_ID_OR_EPOCH = "INVALID_BRIBE_ID_OR_EPOCH"
VOTER_HAS_ALREADY_CLAIMED_BRIBE = "VOTER_HAS_ALREADY_CLAIMED_BRIBE"

# Gauge
NO_STAKE_TO_WITHDRAW = "NO_STAKE_TO_WITHDRAW"
ZERO_STAKE_NOT_ALLOWED = "ZERO_STAKE_NOT_ALLOWED"
SENDER_DOES_NOT_OWN_LOCK = "SENDER_DOES_NOT_OWN_LOCK"
ZERO_WITHDRAWAL_NOT_ALLOWED = "ZERO_WITHDRAWAL_NOT_ALLOWED"
ALREADY_RECHARGED_FOR_EPOCH = "ALREADY_RECHARGED_FOR_EPOCH"

# Fee Distributor
INVALID_TOKEN = "INVALID_TOKEN"
FEES_NOT_YET_ADDED = "FEES_NOT_YET_ADDED"
ALREADY_ADDED_FEES_FOR_EPOCH = "ALREADY_ADDED_FEES_FOR_EPOCH"
VOTER_ALREADY_CLAIMED_FEES_FOR_EPOCH = "VOTER_ALREADY_CLAIMED_FEES_FOR_EPOCH"

# VE Swap
NOTHING_TO_CLAIM = "NOTHING_TO_CLAIM"
SWAP_YET_TO_BEGIN = "SWAP_YET_TO_BEGIN"
CLAIMING_BEFORE_24_HOURS = "CLAIMING_BEFORE_24_HOURS"

# Core Factory
AMM_INVALID = "AMM_INVALID"
AMM_ALREADY_ADDED = "AMM_ALREADY_ADDED"
NO_ADMIN_PROPOSED = "NO_ADMIN_PROPOSED"

# Generic
INVALID_VIEW = "INVALID_VIEW"
NOT_AUTHORISED = "NOT_AUTHORISED"
CONTRACT_DOES_NOT_ACCEPT_TEZ = "CONTRACT_DOES_NOT_ACCEPT_TEZ"
ENTRYPOINT_DOES_NOT_ACCEPT_TEZ = "ENTRYPOINT_DOES_NOT_ACCEPT_TEZ"
AMM_INVALID_OR_NOT_WHITELISTED = "AMM_INVALID_OR_NOT_WHITELISTED"
